//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.2 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.09.17 at 04:19:12 PM CEST 
//


package com.pidev.poc.jaxb;

import javax.xml.bind.annotation.*;
import javax.xml.datatype.XMLGregorianCalendar;
import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.List;


/**
 * <p>Java class for DataType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="DataType"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="Operation" type="{http://aaa.hr/test/v0/DataDetails}Operation"/&gt;
 *         &lt;element name="Origin" type="{http://aaa.hr/test/v0/DataDetails}OfficeType"/&gt;
 *         &lt;element name="Destination" type="{http://aaa.hr/test/v0/DataDetails}OfficeType"/&gt;
 *         &lt;element name="DateOfStart" type="{http://aaa.hr/test/v0/simpleTypes}DateType" minOccurs="0"/&gt;
 *         &lt;element name="AccountValue" type="{http://aaa.hr/test/v0/simpleTypes}Decimal_9_2" minOccurs="0"/&gt;
 *         &lt;element name="Exporter" type="{http://aaa.hr/test/v0/DataDetails}OfficeType" minOccurs="0"/&gt;
 *         &lt;element name="VisitingLocations" type="{http://aaa.hr/test/v0/DataDetails}OfficeType" maxOccurs="9" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "DataType", propOrder = {
    "operation",
    "origin",
    "destination",
    "dateOfStart",
    "accountValue",
    "exporter",
    "visitingLocations"
})
public class DataType {

    @XmlElement(name = "Operation", required = true)
    protected Operation operation;
    @XmlElement(name = "Origin", required = true)
    protected OfficeType origin;
    @XmlElement(name = "Destination", required = true)
    protected OfficeType destination;
    @XmlElement(name = "DateOfStart")
    @XmlSchemaType(name = "date")
    protected XMLGregorianCalendar dateOfStart;
    @XmlElement(name = "AccountValue")
    protected BigDecimal accountValue;
    @XmlElement(name = "Exporter")
    protected OfficeType exporter;
    @XmlElement(name = "VisitingLocations")
    protected List<OfficeType> visitingLocations;

    /**
     * Gets the value of the operation property.
     * 
     * @return
     *     possible object is
     *     {@link Operation }
     *     
     */
    public Operation getOperation() {
        return operation;
    }

    /**
     * Sets the value of the operation property.
     * 
     * @param value
     *     allowed object is
     *     {@link Operation }
     *     
     */
    public void setOperation(Operation value) {
        this.operation = value;
    }

    /**
     * Gets the value of the origin property.
     * 
     * @return
     *     possible object is
     *     {@link OfficeType }
     *     
     */
    public OfficeType getOrigin() {
        return origin;
    }

    /**
     * Sets the value of the origin property.
     * 
     * @param value
     *     allowed object is
     *     {@link OfficeType }
     *     
     */
    public void setOrigin(OfficeType value) {
        this.origin = value;
    }

    /**
     * Gets the value of the destination property.
     * 
     * @return
     *     possible object is
     *     {@link OfficeType }
     *     
     */
    public OfficeType getDestination() {
        return destination;
    }

    /**
     * Sets the value of the destination property.
     * 
     * @param value
     *     allowed object is
     *     {@link OfficeType }
     *     
     */
    public void setDestination(OfficeType value) {
        this.destination = value;
    }

    /**
     * Gets the value of the dateOfStart property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getDateOfStart() {
        return dateOfStart;
    }

    /**
     * Sets the value of the dateOfStart property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setDateOfStart(XMLGregorianCalendar value) {
        this.dateOfStart = value;
    }

    /**
     * Gets the value of the accountValue property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getAccountValue() {
        return accountValue;
    }

    /**
     * Sets the value of the accountValue property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setAccountValue(BigDecimal value) {
        this.accountValue = value;
    }

    /**
     * Gets the value of the exporter property.
     * 
     * @return
     *     possible object is
     *     {@link OfficeType }
     *     
     */
    public OfficeType getExporter() {
        return exporter;
    }

    /**
     * Sets the value of the exporter property.
     * 
     * @param value
     *     allowed object is
     *     {@link OfficeType }
     *     
     */
    public void setExporter(OfficeType value) {
        this.exporter = value;
    }

    /**
     * Gets the value of the visitingLocations property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the visitingLocations property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getVisitingLocations().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link OfficeType }
     * 
     * 
     */
    public List<OfficeType> getVisitingLocations() {
        if (visitingLocations == null) {
            visitingLocations = new ArrayList<OfficeType>();
        }
        return this.visitingLocations;
    }

    @Override
    public String toString() {
        return "DataType{" +
                "operation=" + operation +
                ", origin=" + origin +
                ", destination=" + destination +
                ", dateOfStart=" + dateOfStart +
                ", accountValue=" + accountValue +
                ", exporter=" + exporter +
                ", visitingLocations=" + visitingLocations +
                '}';
    }
}
