//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.2 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.09.17 at 04:19:12 PM CEST 
//


package com.pidev.poc.jaxb;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the hr.aaa.test.v0.datadetails package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _DataDetails_QNAME = new QName("http://aaa.hr/test/v0/DataDetails", "DataDetails");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: hr.aaa.test.v0.datadetails
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link DataDetailsType }
     * 
     */
    public DataDetailsType createDataDetailsType() {
        return new DataDetailsType();
    }

    /**
     * Create an instance of {@link DataType }
     * 
     */
    public DataType createDataType() {
        return new DataType();
    }

    /**
     * Create an instance of {@link Operation }
     * 
     */
    public Operation createOperation() {
        return new Operation();
    }

    /**
     * Create an instance of {@link OfficeType }
     * 
     */
    public OfficeType createOfficeType() {
        return new OfficeType();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link DataDetailsType }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link DataDetailsType }{@code >}
     */
    @XmlElementDecl(namespace = "http://aaa.hr/test/v0/DataDetails", name = "DataDetails")
    public JAXBElement<DataDetailsType> createDataDetails(DataDetailsType value) {
        return new JAXBElement<DataDetailsType>(_DataDetails_QNAME, DataDetailsType.class, null, value);
    }

}
